---
- name: Set up modules for all instances
  hosts: main
  vars_files:
    - variables/docker.yaml
    - variables/couchdb.yaml
  gather_facts: yes
  become: yes
  roles:
    - role: chrony
    - role: docker
    - role: couchdb
    - role: database
    - role: public_keys
